### ISSUE TITLE
create 5 to 10 questions to be reviewed on the next meeting 

### ISSUE THREAD

**Issue by wierdlygoodcoder** [wierdlygoodcoder/hackathon-team-7#1]
please come up with 5 questions  for review tomorrow night

**Comment by andresfgc** [comment]
Questions:

1. In which FIFA world cup was "Waka Waka" played? 2002, 2006, **2010**, 2014
2. Who sings the song "La camisa negra"? Ricky Martin, enrique Iglesias, **Juanes**, Luis Fonsi
3. The intro song is from: despacito, gasolina, danza kuduro, duda (will need a song)
4. Where was the artist "Sia" born? US, Canada, **Australia**, New Zealand
5. What artist has released the most albums? Buckethead, Frank Zappa, Elvis Presley, **Masami Akita**
6. What musical rhythm is this? Salsa, Vallenato, Merengue, Bachata (will need a song)
7. Where has the highest-attended concert been held?Moscow, **Rio de Janeiro**, Paris, Philadelphia
8. The average time listening to music per week is: 2h, 6h, 12h, **18h**
9. The Mozart effect is related to: **classical music**, vocal music, hip hop music, reggae
10. The oldest musical instrument found to date is a: trumpet, **flute**, lithophone, bullroarer

**Comment by KonstantinaStrantzali** [comment]
If the main idea of ​​the project has changed, could the current issue be closed?
