### ISSUE TITLE
Write the questions and answers choices

### ISSUE THREAD

**Issue by KonstantinaStrantzali** [wierdlygoodcoder/hackathon-team-7#11]
In the script.js file there is an array of object the fields of which need to be filled with the questions and answers you found following the form of the first object. Please put the number of the correct answer as well.

**Comment by andresfgc** [comment]
morning!
I just did it.
I could only save it with CRTL+S but I can't use the "git add ." command.
Could you please check and let mw know if you also see the 8 questions?

I added 8 of 10, the other two needed the song sound inside the game.
